function [intensity] = uf_beam_inten(varargin); 

%  [intensity] = uf_beam_inten(aperture,x,y,z);
%
%  Calculates beam intensity at the points specified by vectors x, y and z
%  This intensity is found using calc_hp and the aperture specified by 
%  handle - it may be transmit or receive.  This is the one-way response - 
%  what an ideal hydrophone would measure at a given point.  Intensity is 
%  calculated by summing the squared signal generated by calc_hp.
%
%
%  [intensity = uf_beam_inten(aperture1,aperture2,x,y,z);
%
%  calculates the 
%  two-way response - the intensity recorded by aperture2 in response to 
%  a point target at a given point illuminated by aperture 1.  This 
%  mode uses calc_hhp.  Intensity is calculated as the sum of the squared
%  signal returned by calc_hhp.


if nargin==4

    tx=varargin{1};
    x=varargin{2};
    y=varargin{3};
    z=varargin{4};
    

    for nx=1:length(x),
	    for ny=1:length(y),
		    for nz=1:length(z),
			    [hp,start_time]=calc_hp(tx,[x(nx) y(ny) z(nz)]);
			    intensity(nx,ny,nz)=sum(hp.^2);
		    end;
		end;
    end;
	
elseif nargin==5
    tx=varargin{1};
    rx=varargin{2};
    x=varargin{3};
    y=varargin{4};
    z=varargin{5};
    
    for nx=1:length(x),
	    for ny=1:length(y),
		    for nz=1:length(z),
			    [hp,start_time]=calc_hhp(tx,rx,[x(nx) y(ny) z(nz)]);
			    intensity(nx,ny,nz)=sum(hp.^2);
            end;
		end;   
    end;

else
    error('Wrong number of inputs, see help');    
end;







